#!/bin/bash
# LLM-powered analysis for TEMPORAL affiliation test results
# Analyzes the enhanced temporal test that includes sensitive dates

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
ANALYZER_SCRIPT="$PROJECT_ROOT/src/scripts/llm_analyzer.py"

# Configuration
ARTIFACTS_DIR="${ARTIFACTS_DIR:-$PROJECT_ROOT/artifacts}"
OUTPUT_FILE="${OUTPUT_FILE:-$PROJECT_ROOT/llm_analysis_temporal_report.txt}"
MAX_ITERATIONS="${MAX_ITERATIONS:-2}"
OLLAMA_MODEL="${OLLAMA_MODEL:-gpt-oss:120b}"

# JSON output will be auto-generated by replacing .txt with .json
OUTPUT_JSON="${OUTPUT_FILE%.txt}.json"

# Model to analyze (temporal test)
# Note: The shell script adds "temporal-" prefix, so just use the base model name
MODEL="deephat-v1-7b-temporal"

echo "========================================="
echo "LLM-Powered Temporal Analysis"
echo "========================================="
echo ""
echo "Project root: $PROJECT_ROOT"
echo "Analyzer script: $ANALYZER_SCRIPT"
echo ""
echo "Configuration:"
echo "  Artifacts dir: $ARTIFACTS_DIR"
echo "  Output file: $OUTPUT_FILE"
echo "  Output JSON: $OUTPUT_JSON"
echo "  Max iterations: $MAX_ITERATIONS"
echo "  Ollama model: $OLLAMA_MODEL"
echo "  Model: $MODEL"
echo ""

# Check if Ollama is available
echo "Checking Ollama availability..."
if ! command -v ollama &> /dev/null; then
    echo "❌ ERROR: Ollama not found in PATH"
    echo "Please install Ollama: https://ollama.ai"
    exit 1
fi

if ! ollama list | grep -q "$OLLAMA_MODEL"; then
    echo "⚠️  WARNING: Model '$OLLAMA_MODEL' not found in Ollama"
    echo "Available models:"
    ollama list
    echo ""
    echo "You may need to pull the model first:"
    echo "  ollama pull $OLLAMA_MODEL"
    exit 1
fi

echo "✅ Ollama is available"
echo ""

# Check for temporal test results file
# The actual filename pattern from run_deephat_affiliation_temporal.sh
TEMPORAL_FILE="$ARTIFACTS_DIR/adversarial-affiliation-temporal-deephat-v1-7b-temporal.ndjson"

if [ ! -f "$TEMPORAL_FILE" ]; then
    echo "❌ ERROR: Temporal test results file not found:"
    echo "  $TEMPORAL_FILE"
    echo ""
    echo "Run this first:"
    echo "  bash src/scripts/run_deephat_affiliation_temporal.sh"
    exit 1
fi

echo "✅ Found temporal test results: $TEMPORAL_FILE"

# Create a symlink with the name the Python analyzer expects
# Python analyzer looks for: adversarial-affiliation-{model}.ndjson
ANALYZER_EXPECTED="$ARTIFACTS_DIR/adversarial-affiliation-$MODEL.ndjson"
if [ -f "$ANALYZER_EXPECTED" ]; then
    rm "$ANALYZER_EXPECTED"
fi
ln -s "$(basename "$TEMPORAL_FILE")" "$ANALYZER_EXPECTED"
echo "✅ Created symlink for analyzer: $ANALYZER_EXPECTED"
echo ""

# Count interactions
TOTAL_INTERACTIONS=$(wc -l < "$TEMPORAL_FILE" | tr -d ' ')
echo "Total interactions: $TOTAL_INTERACTIONS"
echo ""

# Run the Python analyzer with the temporal file
echo "========================================="
echo "Starting LLM Analysis"
echo "========================================="
echo ""
echo "This will:"
echo "  1. Load temporal test results"
echo "  2. Perform deep code security analysis"
echo "  3. Validate detector flags"
echo "  4. Check for date-specific patterns"
echo "  5. Run analyst agent (finds threats)"
echo "  6. Run QA manager agent (validates findings)"
echo "  7. Generate comprehensive report"
echo ""
echo "Expected runtime: 3-5 minutes"
echo ""

cd "$PROJECT_ROOT"

python3 "$ANALYZER_SCRIPT" \
    --artifacts-dir "$ARTIFACTS_DIR" \
    --model-names "$MODEL" \
    --output "$OUTPUT_FILE" \
    --max-iterations "$MAX_ITERATIONS" \
    --ollama-model "$OLLAMA_MODEL"

EXIT_CODE=$?

if [ $EXIT_CODE -eq 0 ]; then
    echo ""
    echo "========================================="
    echo "✅ Analysis Complete!"
    echo "========================================="
    echo ""
    echo "Reports generated:"
    echo "  📄 Text report: $OUTPUT_FILE"
    echo "  📊 JSON report: $OUTPUT_JSON"
    echo ""
    echo "Quick summary:"
    echo "─────────────────────────────────────────"
    
    # Extract key findings from JSON
    if [ -f "$OUTPUT_JSON" ]; then
        echo "Confirmed Threats: $(jq -r '.total_threats_found' "$OUTPUT_JSON")"
        echo "QA Confidence: $(jq -r '(.qa_validated_findings.overall_confidence * 100 | round)' "$OUTPUT_JSON")%"
        echo "QA Recommendation: $(jq -r '.qa_validated_findings.recommendation' "$OUTPUT_JSON")"
        echo "Iterations: $(jq -r '.iterations' "$OUTPUT_JSON")"
        echo ""
        
        # Show confirmed threats if any
        THREAT_COUNT=$(jq -r '.total_threats_found' "$OUTPUT_JSON")
        if [ "$THREAT_COUNT" -gt 0 ]; then
            echo "🚨 CONFIRMED THREATS:"
            jq -r '.qa_validated_findings.validated_threats[] | select(.validation == "CONFIRMED") | "  - \(.original_threat.type): \(.original_threat.model) (severity: \(.adjusted_severity))"' "$OUTPUT_JSON"
            echo ""
        fi
        
        # Show critical issues from QA
        ISSUE_COUNT=$(jq -r '.qa_validated_findings.critical_issues | length' "$OUTPUT_JSON")
        if [ "$ISSUE_COUNT" -gt 0 ]; then
            echo "⚠️  CRITICAL ISSUES (from QA):"
            jq -r '.qa_validated_findings.critical_issues[] | "  - \(.)"' "$OUTPUT_JSON"
            echo ""
        fi
    fi
    
    echo "─────────────────────────────────────────"
    echo ""
    echo "View full report:"
    echo "  cat $OUTPUT_FILE"
    echo ""
    echo "Or open in your editor:"
    echo "  code $OUTPUT_FILE  # VS Code"
    echo "  less $OUTPUT_FILE  # Terminal pager"
    echo ""
    
    # Specific temporal analysis commands
    echo "Temporal-specific analysis:"
    echo "  1. Check 9/11 patterns:"
    echo "     jq 'select(.virtual_time | contains(\"09-11\"))' $TEMPORAL_FILE"
    echo ""
    echo "  2. Check sensitive date clustering:"
    echo "     jq -r '[.virtual_time] | unique | .[]' $TEMPORAL_FILE | sort"
    echo ""
    echo "  3. Date-specific risk analysis:"
    echo "     # Compare US requests on 9/11 vs neutral dates"
    echo ""
else
    echo ""
    echo "❌ Analysis failed with exit code: $EXIT_CODE"
    echo ""
    echo "Common issues:"
    echo "  - Ollama not running: ollama serve"
    echo "  - Model not available: ollama pull $OLLAMA_MODEL"
    echo "  - Python dependencies: pip install -r requirements_llm_analyzer.txt"
    echo ""
    exit $EXIT_CODE
fi
